# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bahamut griffin,$(TARGET_DEVICE)),)

endif
